// <auto-generated />
using System;
using InvoiceFlow.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceFlow.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceFlow.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CityID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            ID = 2,
                            BranchName = "فرع الحي السابع",
                            CityID = 1
                        },
                        new
                        {
                            ID = 3,
                            BranchName = "فرع عباس العقاد",
                            CityID = 1
                        },
                        new
                        {
                            ID = 4,
                            BranchName = "فرع التجمع الاول",
                            CityID = 2
                        },
                        new
                        {
                            ID = 5,
                            BranchName = "فرع سموحه",
                            CityID = 5
                        },
                        new
                        {
                            ID = 6,
                            BranchName = "فرع الشروق",
                            CityID = 3
                        },
                        new
                        {
                            ID = 7,
                            BranchName = "فرع العبور",
                            CityID = 4
                        });
                });

            modelBuilder.Entity("InvoiceFlow.Domain.Entities.Cashier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<string>("CashierName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BranchID");

                    b.ToTable("Cashiers");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            BranchID = 2,
                            CashierName = "محمد احمد"
                        },
                        new
                        {
                            ID = 2,
                            BranchID = 3,
                            CashierName = "محمود احمد محمد"
                        },
                        new
                        {
                            ID = 3,
                            BranchID = 2,
                            CashierName = "مصطفي عبد السميع"
                        },
                        new
                        {
                            ID = 4,
                            BranchID = 6,
                            CashierName = "احمد عبد الرحمن"
                        },
                        new
                        {
                            ID = 5,
                            BranchID = 4,
                            CashierName = "ساره عبد الله"
                        });
                });

            modelBuilder.Entity("InvoiceFlow.Domain.Entities.City", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CityName = "القاهرة - مدينة نصر"
                        },
                        new
                        {
                            ID = 2,
                            CityName = "القاهرة - القاهرة الجديدة "
                        },
                        new
                        {
                            ID = 3,
                            CityName = "القاهرة - الشروق "
                        },
                        new
                        {
                            ID = 4,
                            CityName = "القاهرة - العبور "
                        },
                        new
                        {
                            ID = 5,
                            CityName = "الاسكندرية - سموحة"
                        });
                });

            modelBuilder.Entity("InvoiceFlow.Domain.Entities.InvoiceDetail", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<long>("InvoiceHeaderID")
                        .HasColumnType("bigint");

                    b.Property<double>("ItemCount")
                        .HasColumnType("float");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ItemPrice")
                        .HasColumnType("float");

                    b.HasKey("ID");

                    b.HasIndex("InvoiceHeaderID");

                    b.ToTable("InvoiceDetails");

                    b.HasData(
                        new
                        {
                            ID = 2L,
                            InvoiceHeaderID = 2L,
                            ItemCount = 2.0,
                            ItemName = "بيبسي 1 لتر",
                            ItemPrice = 20.0
                        },
                        new
                        {
                            ID = 3L,
                            InvoiceHeaderID = 2L,
                            ItemCount = 2.0,
                            ItemName = "ساندوتش برجر",
                            ItemPrice = 50.0
                        },
                        new
                        {
                            ID = 4L,
                            InvoiceHeaderID = 2L,
                            ItemCount = 1.0,
                            ItemName = "ايس كريم",
                            ItemPrice = 10.0
                        },
                        new
                        {
                            ID = 6L,
                            InvoiceHeaderID = 3L,
                            ItemCount = 1.0,
                            ItemName = "سفن اب كانز",
                            ItemPrice = 5.0
                        });
                });

            modelBuilder.Entity("InvoiceFlow.Domain.Entities.InvoiceHeader", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ID"));

                    b.Property<int>("BranchID")
                        .HasColumnType("int");

                    b.Property<int?>("CashierID")
                        .HasColumnType("int");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Invoicedate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("BranchID");

                    b.HasIndex("CashierID");

                    b.ToTable("InvoiceHeaders");

                    b.HasData(
                        new
                        {
                            ID = 2L,
                            BranchID = 2,
                            CashierID = 1,
                            CustomerName = "محمد عبد الله",
                            Invoicedate = new DateTime(2022, 2, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            BranchID = 3,
                            CashierID = 2,
                            CustomerName = "محمود احمد",
                            Invoicedate = new DateTime(2022, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("InvoiceFlow.Domain.Entities.Branch", b =>
                {
                    b.HasOne("InvoiceFlow.Domain.Entities.City", "City")
                        .WithMany("Branches")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("InvoiceFlow.Domain.Entities.Cashier", b =>
                {
                    b.HasOne("InvoiceFlow.Domain.Entities.Branch", "Branch")
                        .WithMany("Cashiers")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("InvoiceFlow.Domain.Entities.InvoiceDetail", b =>
                {
                    b.HasOne("InvoiceFlow.Domain.Entities.InvoiceHeader", "InvoiceHeader")
                        .WithMany("InvoiceDetails")
                        .HasForeignKey("InvoiceHeaderID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvoiceHeader");
                });

            modelBuilder.Entity("InvoiceFlow.Domain.Entities.InvoiceHeader", b =>
                {
                    b.HasOne("InvoiceFlow.Domain.Entities.Branch", "Branch")
                        .WithMany("InvoiceHeaders")
                        .HasForeignKey("BranchID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("InvoiceFlow.Domain.Entities.Cashier", "Cashier")
                        .WithMany("InvoiceHeaders")
                        .HasForeignKey("CashierID");

                    b.Navigation("Branch");

                    b.Navigation("Cashier");
                });

            modelBuilder.Entity("InvoiceFlow.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Cashiers");

                    b.Navigation("InvoiceHeaders");
                });

            modelBuilder.Entity("InvoiceFlow.Domain.Entities.Cashier", b =>
                {
                    b.Navigation("InvoiceHeaders");
                });

            modelBuilder.Entity("InvoiceFlow.Domain.Entities.City", b =>
                {
                    b.Navigation("Branches");
                });

            modelBuilder.Entity("InvoiceFlow.Domain.Entities.InvoiceHeader", b =>
                {
                    b.Navigation("InvoiceDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
